### ISSUE TITLE
How to change pod's egress to the Elastic IP?

### ISSUE THREAD

**Issue by NinoSkopac** [aws-samples/aws-pod-eip-controller#157]
So, I want internet connection going out on the EIP instead on the primary ENI.

How?

Thanks!

This thing is cool!

**Comment by NinoSkopac** [comment]
Aka how to change default internet gateway from primary ENI to attached EIP, in the pod?

**Comment by NinoSkopac** [comment]
More info

Start Alpine 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      annotations:
        aws-samples.github.com/aws-pod-eip-controller-type: auto
      labels:
        app: alpine
    spec:
      containers:
        - name: alpine
          image: alpine:latest
          command: [ "sleep" ]
          args: [ "infinity" ]
```

Shell into it
```bash
kubectl exec -it alpine-7566fff7d9-ml7h6 -- /bin/sh

/ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: eth0@if18: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 9001 qdisc noqueue state UP 
    link/ether b6:7d:94:06:9c:3c brd ff:ff:ff:ff:ff:ff
    inet 10.0.23.33/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::b47d:94ff:fe06:9c3c/64 scope link 
       valid_lft forever preferred_lft forever
/ # ip route 
default via 169.254.1.1 dev eth0 
169.254.1.1 dev eth0 scope link 
```

how to route to the thing
