### ISSUE TITLE
How is Service.NodePort handled?

### ISSUE THREAD

**Issue by NinoSkopac** [aws-samples/aws-pod-eip-controller#164]
My use case
P2P client requiring full cone NAT on 56000-56100/udp. In other words, unsolicited connections must come in. ( reason why I'm using EIP controller. )

I have full cone NAT working thanks to this controller but the p2p connections in the pod die a few seconds after establishing connection. "Timeout waiting for reply".

So, I'm wondering...is this even supposed to work?  I can describe the svc and see it's bound to pod's internal IP.

let me try to illustrate my use case (p2p connections):
1. my pod with eip listens on a range of ports
2. at any time, a connection can come in and it must be forwarded to be pod

My question: is the incoming connection gonna come in the "right way"?

I did try without a Svc and Ports altogether - same error.

Using `hostNetwork: true` does work, but at an expense of security and scalability, so I'm trying not to use that.

Thanks for the great work on this thing

**Comment by turmind** [comment]
Pod as ech-server, echo-cli log:

```
Message sent:  Hello World 0
{"level":"info","msg":"Use time: 389.406µs Message received: received message from 18.142.xx.xx:16632, content is: Hello World 0\n","time":"2024-07-24T13:00:36Z"}
Message sent:  Hello World 1
{"level":"info","msg":"Use time: 322.549µs Message received: received message from 18.142.xx.xx:16632, content is: Hello World 1\n","time":"2024-07-24T13:00:37Z"}
Message sent:  Hello World 2
{"level":"info","msg":"Use time: 378.143µs Message received: received message from 18.142.xx.xx:16632, content is: Hello World 2\n","time":"2024-07-24T13:00:38Z"}
Message sent:  Hello World 3
{"level":"info","msg":"Use time: 500.08µs Message received: received message from 18.142.xx.xx:16632, content is: Hello World 3\n","time":"2024-07-24T13:00:39Z"}
Message sent:  Hello World 4
{"level":"info","msg":"Use time: 365.771µs Message received: received message from 18.142.xx.xx:16632, content is: Hello World 4\n","time":"2024-07-24T13:00:40Z"}
```

Pod as echo-cli, log:

```
Message sent:  Hello World 0
{"level":"info","msg":"Use time: 428.079µs Message received: received message from 3.1.xx.xx:37710, content is: Hello World 0\n","time":"2024-07-24T12:59:52Z"}
Message sent:  Hello World 1
{"level":"info","msg":"Use time: 392.327µs Message received: received message from 3.1.xx.xx:37710, content is: Hello World 1\n","time":"2024-07-24T12:59:53Z"}
Message sent:  Hello World 2
{"level":"info","msg":"Use time: 420.463µs Message received: received message from 3.1.xx.xx:37710, content is: Hello World 2\n","time":"2024-07-24T12:59:54Z"}
Message sent:  Hello World 3
{"level":"info","msg":"Use time: 402.71µs Message received: received message from 3.1.xx.xx:37710, content is: Hello World 3\n","time":"2024-07-24T12:59:55Z"}
Message sent:  Hello World 4
{"level":"info","msg":"Use time: 374.354µs Message received: received message from 3.1.xx.xx:37710, content is: Hello World 4\n","time":"2024-07-24T12:59:56Z"}
```

**Comment by NinoSkopac** [comment]
That’s great info regarding UDP timeout, thank you for pointing that out. I felt something like that could be the issue, but I wasn’t aware that there is an actual timeout somewhere in the VPC settings. I’ll look into heart beat interval of the software I’m trying to run. 

The security group is set up correctly, and it does allow unsolicited ingress, which I confirmed with pystun3 which came back as full cone nat. 

May i ask, were you using NodePorts and Svc when trying the udp workshop? 

Finally, may i digress slightly and focus on what you said:

> Judging from the normal use of hostNetwork: true

It’s my understanding hostNetwork is for unusual use cases, which this definitely is, so I understand it’s normal in this case, but it’s also a huge pain in regards to scalability. My goal is to get rid of it. The codebase/container I’m doing it for is https://github.com/mysteriumnetwork/node. Any suggestions on how to accomplish it are greatly appreciated as have been your past suggestions and i understand it’s out of scope so feel free to close this whenever you want as you did answer my question just perfectly. Thank you for taking the time. 

Regards,
Nino

**Comment by NinoSkopac** [comment]
I just realized it might not be the UDP timeout as the software works fine on ec2/docker on ec2, and it's my understanding that this UDP timeout is specific to the VPC, not to K8s.

**Comment by turmind** [comment]
> That’s great info regarding UDP timeout, thank you for pointing that out. I felt something like that could be the issue, but I wasn’t aware that there is an actual timeout somewhere in the VPC settings. I’ll look into heart beat interval of the software I’m trying to run.
> 
> The security group is set up correctly, and it does allow unsolicited ingress, which I confirmed with pystun3 which came back as full cone nat.
> 
> May i ask, were you using NodePorts and Svc when trying the udp workshop? Or no Svc at all?
> 
> Finally, may i digress slightly and focus on what you said:
> 
> > Judging from the normal use of hostNetwork: true
> 
> It’s my understanding hostNetwork is for unusual use cases, which this definitely is, so I understand it’s normal in this case, but it’s also a huge pain in regards to scalability. My goal is to get rid of it. The codebase/container I’m doing it for is https://github.com/mysteriumnetwork/node. Any suggestions on how to accomplish it are greatly appreciated as have been your past suggestions and i understand it’s out of scope so feel free to close this whenever you want as you did answer my question just perfectly. Thank you for taking the time.
> 
> Regards, Nino

Neither use Nodeport nor SVC, Direct access through the EIP bound to the Pod. Deployment yaml's spec is：

```
    spec:
      serviceAccountName: echo-user
      containers:
      - image: xxxx.dkr.ecr.ap-southeast-1.amazonaws.com/echo-server
        name: echo-server
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8081
          protocol: UDP
        - containerPort: 8082
          protocol: TCP
        volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
      initContainers:
      - image: busybox:1.28
        name: innit
        command: ['timeout', '-t' ,'60', 'sh','-c', "until grep -E '^aws-pod-eip-controller-public-ip?' /etc/podinfo/labels; do echo waiting for labels; sleep 2; done"]
        volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
      volumes:
        - name: podinfo
          downwardAPI:
            items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
```
